</$objtype/mkfile
BIN=/$objtype/bin

TARG=try
OFILES=\
	try.$O\

HFILES=\
	try.h\

LIB=\
	../libgraphics/libgraphics.a$O\
	../libgeometry/libgeometry.a$O\

CFLAGS=$CFLAGS -I. -I../libgeometry -I../libgraphics -I../librender

</sys/src/cmd/mkone

../libgeometry/libgeometry.a$O:
	cd ../libgeometry
	mk install

../libgraphics/libgraphics.a$O:
	cd ../libgraphics
	mk install

clean nuke:V:
	rm -f *.[$OS] [$OS].out $TARG
	@{cd ../libgeometry; mk $target}
	@{cd ../libgraphics; mk $target}
